-- Hot path indexes for feed, dashboard, chat, notifications, orders, and quote flows.

CREATE INDEX IF NOT EXISTS "ChatMessage_roomId_createdAt_idx" ON "ChatMessage"("roomId", "createdAt");
CREATE INDEX IF NOT EXISTS "ChatMessage_senderId_createdAt_idx" ON "ChatMessage"("senderId", "createdAt");
CREATE INDEX IF NOT EXISTS "ChatRoom_user1Id_updatedAt_idx" ON "ChatRoom"("user1Id", "updatedAt");
CREATE INDEX IF NOT EXISTS "ChatRoom_user2Id_updatedAt_idx" ON "ChatRoom"("user2Id", "updatedAt");
CREATE INDEX IF NOT EXISTS "Collection_storeId_createdAt_idx" ON "Collection"("storeId", "createdAt");
CREATE INDEX IF NOT EXISTS "CollectionPiece_pieceId_idx" ON "CollectionPiece"("pieceId");
CREATE INDEX IF NOT EXISTS "Comment_postId_parentId_createdAt_idx" ON "Comment"("postId", "parentId", "createdAt");
CREATE INDEX IF NOT EXISTS "Comment_userId_createdAt_idx" ON "Comment"("userId", "createdAt");
CREATE INDEX IF NOT EXISTS "CommentLike_userId_createdAt_idx" ON "CommentLike"("userId", "createdAt");
CREATE INDEX IF NOT EXISTS "InspirationImage_quoteInquiryId_idx" ON "InspirationImage"("quoteInquiryId");
CREATE INDEX IF NOT EXISTS "MeasurementProfile_userId_updatedAt_idx" ON "MeasurementProfile"("userId", "updatedAt");
CREATE INDEX IF NOT EXISTS "Notification_userId_createdAt_idx" ON "Notification"("userId", "createdAt");
CREATE INDEX IF NOT EXISTS "Notification_userId_type_createdAt_idx" ON "Notification"("userId", "type", "createdAt");
CREATE INDEX IF NOT EXISTS "Notification_userId_isRead_createdAt_idx" ON "Notification"("userId", "isRead", "createdAt");
CREATE INDEX IF NOT EXISTS "Order_designerId_status_createdAt_idx" ON "Order"("designerId", "status", "createdAt");
CREATE INDEX IF NOT EXISTS "Order_customerId_createdAt_idx" ON "Order"("customerId", "createdAt");
CREATE INDEX IF NOT EXISTS "Order_status_createdAt_idx" ON "Order"("status", "createdAt");
CREATE INDEX IF NOT EXISTS "OrderTimeline_orderId_createdAt_idx" ON "OrderTimeline"("orderId", "createdAt");
CREATE INDEX IF NOT EXISTS "Piece_storeId_status_createdAt_idx" ON "Piece"("storeId", "status", "createdAt");
CREATE INDEX IF NOT EXISTS "Piece_category_createdAt_idx" ON "Piece"("category", "createdAt");
CREATE INDEX IF NOT EXISTS "Piece_heritage_createdAt_idx" ON "Piece"("heritage", "createdAt");
CREATE INDEX IF NOT EXISTS "PieceImage_pieceId_order_idx" ON "PieceImage"("pieceId", "order");
CREATE INDEX IF NOT EXISTS "Post_designerId_createdAt_idx" ON "Post"("designerId", "createdAt");
CREATE INDEX IF NOT EXISTS "Post_createdAt_idx" ON "Post"("createdAt");
CREATE INDEX IF NOT EXISTS "Post_quoteEnabled_createdAt_idx" ON "Post"("quoteEnabled", "createdAt");
CREATE INDEX IF NOT EXISTS "Post_isClientRequest_createdAt_idx" ON "Post"("isClientRequest", "createdAt");
CREATE INDEX IF NOT EXISTS "PostLike_userId_createdAt_idx" ON "PostLike"("userId", "createdAt");
CREATE INDEX IF NOT EXISTS "PostMedia_postId_order_idx" ON "PostMedia"("postId", "order");
CREATE INDEX IF NOT EXISTS "Quotation_status_createdAt_idx" ON "Quotation"("status", "createdAt");
CREATE INDEX IF NOT EXISTS "Quotation_updatedAt_idx" ON "Quotation"("updatedAt");
CREATE INDEX IF NOT EXISTS "QuoteInquiry_designerId_status_createdAt_idx" ON "QuoteInquiry"("designerId", "status", "createdAt");
CREATE INDEX IF NOT EXISTS "QuoteInquiry_customerId_createdAt_idx" ON "QuoteInquiry"("customerId", "createdAt");
CREATE INDEX IF NOT EXISTS "QuoteInquiry_pieceId_createdAt_idx" ON "QuoteInquiry"("pieceId", "createdAt");
CREATE INDEX IF NOT EXISTS "QuoteInquiry_measurementProfileId_idx" ON "QuoteInquiry"("measurementProfileId");
CREATE INDEX IF NOT EXISTS "Review_designerId_createdAt_idx" ON "Review"("designerId", "createdAt");
CREATE INDEX IF NOT EXISTS "Review_customerId_createdAt_idx" ON "Review"("customerId", "createdAt");
CREATE INDEX IF NOT EXISTS "ReviewImage_reviewId_idx" ON "ReviewImage"("reviewId");
CREATE INDEX IF NOT EXISTS "SavedPost_userId_createdAt_idx" ON "SavedPost"("userId", "createdAt");
CREATE INDEX IF NOT EXISTS "SupportMessage_ticketId_createdAt_idx" ON "SupportMessage"("ticketId", "createdAt");
CREATE INDEX IF NOT EXISTS "SupportTicket_userId_updatedAt_idx" ON "SupportTicket"("userId", "updatedAt");
CREATE INDEX IF NOT EXISTS "SupportTicket_status_updatedAt_idx" ON "SupportTicket"("status", "updatedAt");
CREATE INDEX IF NOT EXISTS "User_role_idx" ON "User"("role");
CREATE INDEX IF NOT EXISTS "User_isDeleted_createdAt_idx" ON "User"("isDeleted", "createdAt");
